template: testify
packages:
    url-shortener/internal/http-server/handlers/del:
        config:
            dir: "{{.InterfaceDir}}"
            filename: "URLDeleter.go"
            pkgname: "del"
            structname: "Mock{{.InterfaceName}}"
        interfaces:
            URLDeleter: