env: "local"
storage_path: "./storage/storage.db"
app_id: 1
http_server:
  address: "localhost:8082"
  timeout: 4s
  idle_timeout: 60s
  user: "admin"
  password: "123456"
clients:
  sso:
    address: "localhost:44044"
    timeout: 2s
    retriesCount: 2
    insecure: true