env: "prod"
storage_path: "./storage.db"
app_id: 1
http_server:
  address: "0.0.0.0:8082"
  timeout: 4s
  idle_timeout: 30s
  user: "admin"
clients:
  sso:
    address: "127.0.0.1:44044"
    timeout: 2s
    retriesCount: 2
    insecure: true